[package]
name = "mudras"
version = "0.1.0"
edition = "2021"

[dependencies]
bon = "3.6.5"
knus = "3.3.1"
log = "0.4.27"
miette = { version = "7.6.0", features = ["fancy"] }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
